---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vaultwarden-admin
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/vaultwarden
        property: admin_token
