---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: changedetection
spec:
  interval: 24h
  url: https://bjw-s-labs.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
  namespace: changedetection
spec:
  interval: 30m
  timeout: 15m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: "3.*"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: changedetection
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: latest
            env:
              TZ: "Europe/London"
              PORT: "5000"
              PUID: "1000"
              PGID: "1000"
              BASE_URL: "https://changedetection.liberispat.com"
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: 5000

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: zfs-nfs
        globalMounts:
          - path: /datastore

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: akasha
