---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zfs-exporter
  namespace: zfs-exporter
  labels:
    app: zfs-exporter
spec:
  selector:
    matchLabels:
      app: zfs-exporter
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 30s
