---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: democratic-csi-driver-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: zfs-generic-nfs

          sshConnection:
            host: 192.168.10.12
            port: 22
            username: democratic-csi
            privateKey: |
              {{ .ssh_private_key | nindent 14 }}

          zfs:
            cli:
              sudoEnabled: true
              paths:
                zfs: /run/current-system/sw/bin/zfs
                zpool: /run/current-system/sw/bin/zpool
                sudo: /run/wrappers/bin/sudo
            datasetParentName: tank/k8s/volumes
            detachedSnapshotsDatasetParentName: tank/k8s/snapshots
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
            datasetProperties:
              "org.democratic-csi:pvc_name": "{{ "{{" }} parameters.[csi.storage.k8s.io/pvc/name] {{ "}}" }}"
              "org.democratic-csi:pvc_namespace": "{{ "{{" }} parameters.[csi.storage.k8s.io/pvc/namespace] {{ "}}" }}"

          nfs:
            shareStrategy: setDatasetProperties
            shareStrategySetDatasetProperties:
              properties:
                sharenfs: "rw,no_subtree_check,no_root_squash"
            shareHost: 192.168.10.12
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: secret/democratic-csi
        property: ssh_private_key
