---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mktxp-config
  namespace: mktxp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mktxp-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        mktxp.conf: |
          ## MikroTik devices configuration

          [Router]
              enabled = True
              hostname = {{ .router_host }}
              port = 8728
              username = {{ .username }}
              password = "{{ .password }}"

              use_ssl = False
              no_ssl_certificate = False
              ssl_certificate_verify = False

              installed_packages = True
              dhcp = True
              dhcp_lease = True
              connections = True
              connection_stats = False
              pool = True
              interface = True
              firewall = True
              ipv6_firewall = False
              ipv6_neighbor = False
              poe = False
              monitor = True
              netwatch = True
              public_ip = True
              route = True
              wireless = False
              wireless_clients = False
              capsman = False
              capsman_clients = False
              user = True
              queue = True
              remote_dhcp_entry = None
              check_for_updates = False

          [Switch]
              enabled = True
              hostname = {{ .switch_host }}
              port = 8728
              username = {{ .username }}
              password = "{{ .password }}"

              use_ssl = False
              no_ssl_certificate = False
              ssl_certificate_verify = False

              installed_packages = True
              dhcp = False
              dhcp_lease = False
              connections = False
              connection_stats = False
              pool = False
              interface = True
              firewall = False
              ipv6_firewall = False
              ipv6_neighbor = False
              poe = True
              monitor = True
              netwatch = False
              public_ip = False
              route = False
              wireless = False
              wireless_clients = False
              capsman = False
              capsman_clients = False
              user = True
              queue = False
              remote_dhcp_entry = None
              check_for_updates = False

          [AP]
              enabled = True
              hostname = {{ .ap_host }}
              port = 8728
              username = {{ .username }}
              password = "{{ .password }}"

              use_ssl = False
              no_ssl_certificate = False
              ssl_certificate_verify = False

              installed_packages = True
              dhcp = False
              dhcp_lease = False
              connections = False
              connection_stats = False
              pool = False
              interface = True
              firewall = False
              ipv6_firewall = False
              ipv6_neighbor = False
              poe = False
              monitor = True
              netwatch = False
              public_ip = False
              route = False
              wireless = True
              wireless_clients = True
              capsman = False
              capsman_clients = False
              user = True
              queue = False
              remote_dhcp_entry = None
              check_for_updates = False

        _mktxp.conf: |
          [MKTXP]
              port = 49090
              socket_timeout = 10

              initial_delay_on_failure = 120
              max_delay_on_failure = 900
              delay_inc_div = 5

              bandwidth = False
              bandwidth_test_interval = 600

              minimal_collect_interval = 5

              verbose_mode = False

              fetch_routers_in_parallel = True
              max_worker_threads = 5

              total_max_scrape_duration = 60

              compact_default_conf_values = False

              persistent_router_connection_pool = False
  data:
    - secretKey: router_host
      remoteRef:
        key: secret/mktxp
        property: router_host
    - secretKey: switch_host
      remoteRef:
        key: secret/mktxp
        property: switch_host
    - secretKey: ap_host
      remoteRef:
        key: secret/mktxp
        property: ap_host
    - secretKey: username
      remoteRef:
        key: secret/mktxp
        property: username
    - secretKey: password
      remoteRef:
        key: secret/mktxp
        property: password
