---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mktxp
  namespace: mktxp
  labels:
    app: mktxp
spec:
  selector:
    matchLabels:
      app: mktxp
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 25s
