---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-credentials
  namespace: samba
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: samba-credentials
    creationPolicy: Owner
  data:
    - secretKey: SMB_USER
      remoteRef:
        key: secret/samba
        property: smb_user
    - secretKey: SMB_PASSWORD
      remoteRef:
        key: secret/samba
        property: smb_password
