---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: prowlarr
spec:
  interval: 24h
  url: https://bjw-s-labs.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: "3.*"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: prowlarr
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: linuxserver/prowlarr
              tag: latest
            env:
              TZ: "Europe/London"
              PUID: "1000"
              PGID: "1000"
            probes:
              liveness:
                enabled: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
              readiness:
                enabled: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
              startup:
                enabled: true
                spec:
                  httpGet:
                    path: /ping
                    port: 9696
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: jarvis

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 9696

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: zfs-nfs
        globalMounts:
          - path: /config
