---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvdp
  namespace: kube-system
spec:
  interval: 24h
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: kube-system
  values:
    nodeSelector:
      kubernetes.io/hostname: nixos
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
