---
# GitLab credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-credentials
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitlab-credentials
    creationPolicy: Owner
  data:
    - secretKey: root_password
      remoteRef:
        key: secret/gitlab
        property: root_password
