---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-credentials
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mealie-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin_email
      remoteRef:
        key: secret/mealie
        property: admin_email
    - secretKey: admin_password
      remoteRef:
        key: secret/mealie
        property: admin_password
