---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: koel-env
  namespace: koel
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: koel-env
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        .env: |
          APP_KEY={{ .app_key }}
          DB_CONNECTION=sqlite
          DB_DATABASE=/var/www/html/storage/koel.sqlite
          MEDIA_PATH=/music
          FORCE_HTTPS=true
          APP_URL=https://koel.liberispat.com
          FFMPEG_PATH=/usr/bin/ffmpeg
  data:
    - secretKey: app_key
      remoteRef:
        key: secret/koel
        property: app_key
