---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartctl-exporter
resources:
  - namespace.yaml
  - deployment.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: smartctl-dashboard
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/smartctl.json
