---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adguard-exporter-creds
  namespace: adguard-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: adguard-exporter-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/adguard
        property: username
    - secretKey: password
      remoteRef:
        key: secret/adguard
        property: password
