---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: funkwhale-secrets
  namespace: funkwhale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: funkwhale-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DJANGO_SECRET_KEY: "{{ .django_secret_key }}"
  data:
    - secretKey: django_secret_key
      remoteRef:
        key: secret/funkwhale
        property: django_secret_key
